---
title: "In class examples"
author: "sbsambado"
date: "4/8/2020"
output: html_document
---

In class examples in EEMB 595TE taught by Dr. Stephen Prouxl

April 7th, 2020
```{r}
library(tidyverse)

data = tibble(trial = seq(1,6), outcome = c('W', 'W', 'L', 'W', 'W', 'W'))


# grid likelihood

stepsize = 0.01
likelihood_tab <- tibble(proportion_water = seq(0,1, stepsize), likelihood = 0)
#View(likelihood_tab)

ntot = nrow(data)
nwater = nrow(filter(data, outcome == 'W' ))

likelihood_tab <- mutate(likelihood_tab, likelihood = dbinom(nwater, ntot, proporiton_water))

ggplot(data = likelihood_tab, aes(x = proporiton_water, y = likelihood)) +
  geom_point() +
  theme_bw() 
```

April 9th, 2020
```{r}
# library(rethinking)
data(homeworkch3)
sum(birth1) + sum(birth2)
```

Homework 3E1-7
```{r}
## R code 3.27

p_grid <- seq(0, 1, length.out = 1000)
prior <- rep(1,1000)
likelihood <- dbinom(6, size = 9, prob = p_grid)
posterior <- likelihood * prior
posterior <- posterior / sum(posterior)
set.seed(100)
samples <- sample(p_grid, prob = posterior, size = 14, replace = TRUE)

# 3E1 How much posterior probability lies below p = 0.2?

PI(samples, prob = 0.2)
# 3E2 How much posterior probability lies above p = 0.8?



# 3E3 How much posterior probability lies between p = 0.2 and p = 0.8?


# 3E4 20% of the posterior probability lies below which value of p?


# 3E5 20% of the posterior probability lies above which value of p?


# 3E6 Which values of p contain the narrowest interval equal to 66% of the posterior probability?

# 3E7 Which values of p contain 66% of the posterior probability, assuming equal posterior probability both below and above the interval?

```

